apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.projectName | lower }}-frontend-ingress
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: {{ printf "Host(`%s`)" (.Values.domain) }}
      kind: Rule
      services:
        - name: {{ .Values.projectName | lower }}-frontend-service
          port: {{ .Values.app.frontend.port }}

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.projectName | lower }}-backend-ingress
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: {{ printf "Host(`%s`)" (.Values.domain) }} && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: {{ .Values.projectName | lower }}-backend-service
          port: {{ .Values.app.backend.port }}